version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_local
    ports:
      - 3310:3306
    environment:
      - MYSQL_ROOT_PASSWORD=carlos
    #   - MYSQL_USER=user
    #   - MYSQL_PASSWORD=secret
    #   - MYSQL_DATABASE=database
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_local
    ports:
      - 8100:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysql_data: